name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # or the version you're using
      
    - name: Install Dependencies
      run: |
        cd project
        npm install

    - name: Build and Test
      run: |
        cd project
        npm run build
        npm test
